Lobby 코드 리뷰
SukereamTeam/hamsterisfree pull request #29
Opened 2023-09-25 03:29 UTC by eggmong

# 구현 목표
Game Scene에 진입하기 전 Stage를 선택할 수 있는 Lobby Scene을 구성하고, 관리하는 Manager 클래스를 를 구현했습니다.
스크롤은 [LoopScrollRect Asset](https://github.com/qiankanglai/LoopScrollRect)을 사용했습니다. 

# 주요 구현 사항
## LobbyManager
사용한 스크롤 Asset에선 각 스크롤 아이템의 Initialize 작업을 `ScrollCellIndex` 함수를 통해서 해주고 있습니다.
그래서 `ScrollCellIndex` 함수를 통해 각 아이템에 index를 부여하고,
`OnClick_Item` 함수를 작성하여, 아이템을 클릭했을 때 index를 받아와서
index에 맞는 Stage Data를 로드하여 Game Scene을 호출하도록 했습니다.

2023-09-26 03:34 UTC, BeautyfullCastle requested changes

2023-09-26 03:34 UTC, BeautyfullCastle commented on Assets/Scripts/Lobby/LobbyManager.cs
> +using Demo;
Demo를 안쓰는 것 같은데 지워야 할 것 같습니다.

2023-09-26 03:34 UTC, BeautyfullCastle commented on Assets/Scripts/Lobby/ScrollIndexCallback_StageItem.cs
> +            this.gameObject.GetComponent<Image>().color = Color.blue;
이 함수는 자주 불리기 때문에 컴포넌트는 Start같은 데서 캐싱해두는 게 좋습니다!

2023-09-26 03:34 UTC, BeautyfullCastle commented on Assets/Scripts/Lobby/ScrollIndexCallback_StageItem.cs
> +    private int index = -1;
`index는` 광범위한 이름이므로 cellIndex나 stageIndex가 좋을 것 같습니다!

2023-09-26 03:34 UTC, BeautyfullCastle commented on Assets/Scripts/Lobby/ScrollIndexCallback_StageItem.cs
> +    public async void OnClick_Item()
_를 붙이는 건 따로 규칙이 있나요?
에디터에서 추가하는 콜백 함수에 붙이는 건가요?

2023-09-26 03:34 UTC, BeautyfullCastle commented on Assets/Scripts/Lobby/ScrollIndexCallback_StageItem.cs
> +    public async void OnClick_Item()
아 그리고 저는 async 함수면 뒤에 Async를 붙여서 await을 깜빡하지 않게 하는 편입니다.

2023-09-26 03:34 UTC, BeautyfullCastle commented on Assets/Simple Scroll-Snap/Examples/Example 1 (macOS Finder)/Scripts/FileUI.cs
> +﻿// Simple Scroll-Snap - https://assetstore.unity.com/packages/tools/gui/simple-scroll-snap-140884
전 Example이나 Demo 등의 폴더는 git에서 제외하거나 지워버리는 편인데 참고하시면 좋을 것 같습니다!

2023-09-27 02:54 UTC, eggmong commented on Assets/Scripts/Lobby/LobbyManager.cs
> +using Demo;
넵! 지웠습니다!

2023-09-27 02:58 UTC, eggmong commented on Assets/Scripts/Lobby/ScrollIndexCallback_StageItem.cs
> +            this.gameObject.GetComponent<Image>().color = Color.blue;
```c#
private void Start()
    {
        this.itemImage = this.GetComponent<Image>();
        if (this.itemImage == null)
        {
            Debug.Log("### Not Found StageItem Image Component. ###");
        }
    }
```
요렇게 캐싱 하는 코드를 작성했습니다!

2023-09-27 03:01 UTC, eggmong commented on Assets/Scripts/Lobby/ScrollIndexCallback_StageItem.cs
> +    private int index = -1;
넹! stageIndex로 변경 했습니다!

2023-09-27 03:02 UTC, eggmong commented on Assets/Scripts/Lobby/ScrollIndexCallback_StageItem.cs
> +    public async void OnClick_Item()
_ 를 붙이는 건 그냥 저만의 명명규칙이었는데요...
떼는게 나을까요?

함수명은 Async를 붙이는 것으로 바꿨습니다!

2023-09-27 03:06 UTC, eggmong commented on Assets/Simple Scroll-Snap/Examples/Example 1 (macOS Finder)/Scripts/FileUI.cs
> +﻿// Simple Scroll-Snap - https://assetstore.unity.com/packages/tools/gui/simple-scroll-snap-140884
넵 지워버리도록 하겠습니다!

2023-09-27 08:24 UTC, BeautyfullCastle commented on Assets/Scripts/Lobby/ScrollIndexCallback_StageItem.cs
> +    public async void OnClick_Item()
규칙이 있으면 상관 없습니다! _를 붙이는 규칙을 알려주실 수 있을까요?

2023-09-29 10:15 UTC, eggmong commented on Assets/Scripts/Lobby/ScrollIndexCallback_StageItem.cs
> +    public async void OnClick_Item()
클릭 이벤트에 붙는 함수일 때 OnClick_를 붙입니다!

2023-09-29 15:09 UTC, BeautyfullCastle approved these changes
수고하셔씀다!

2023-09-30 05:43 UTC, merged